variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: micro-auth

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t $PROJECT_GROUP/$PROJECT_NAME .
  tags:
    - shell

test:
  image: kkarczmarczyk/node-yarn
  stage: test
  script:
    - yarn install
    - yarn test
  tags:
    - docker

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=57ac25fd7c00d7282208c92486b851 -F ref=master https://office.cap3.de:52203/api/v4/projects/286/trigger/pipeline"