variables:
  DEPLOYMENT_CONTAINER: waterchat-micro-auth

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - docker build -t <PROJECT-NAME> .
  tags:
    - shell

test:
  image: <PROJECT-NAME>
  stage: test
  script:
    - yarn test
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker stop $DEPLOYMENT_CONTAINER
    - docker rm $DEPLOYMENT_CONTAINER
    - docker run -d -p 3000:3000 --restart=always <PROJECT-NAME> --name=$DEPLOYMENT_CONTAINER
    - docker exec -it $DEPLOYMENT_CONTAINER yarn start
  tags:
    - shell
