variables:
  DEPLOYMENT_IMAGE: waterchat-micro-auth-image
  DEPLOYMENT_CONTAINER: waterchat-micro-auth

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - whoami
    - docker build -t $DEPLOYMENT_IMAGE .
  tags:
    - shell

test:
  image: $DEPLOYMENT_IMAGE
  stage: test
  script:
    - yarn test
  tags:
    - docker
  allow_failure: true

deploy:
  stage: deploy
  script:
    - docker stop $DEPLOYMENT_CONTAINER
    - docker rm $DEPLOYMENT_CONTAINER
    - docker run -d -p 3000:3000 --restart=always $DEPLOYMENT_IMAGE --name=$DEPLOYMENT_CONTAINER
    - docker exec -it $DEPLOYMENT_CONTAINER yarn start
  tags:
    - shell
