variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: micro-auth

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t $PROJECT_GROUP/$PROJECT_NAME .
  tags:
    - shell

test:
  image: kkarczmarczyk/node-yarn
  stage: test
  script:
    - yarn install
    - yarn test
  tags:
    - docker