FROM node:8-alpine

# ENV vars 
ARG GITHUB_CALLBACK 
ARG GITHUB_ID 
ARG GITHUB_SECRET 

ARG TWITTER_CALLBACK 
ARG TWITTER_ID 
ARG TWITTER_SECRET 

ARG FACEBOOK_CALLBACK 
ARG FACEBOOK_ID 
ARG FACEBOOK_SECRET 
 
ENV GITHUB_CALLBACK ${GITHUB_CALLBACK} 
ENV GITHUB_ID ${GITHUB_ID} 
ENV GITHUB_SECRET ${GITHUB_SECRET} 

ENV TWITTER_CALLBACK ${TWITTER_CALLBACK} 
ENV TWITTER_ID ${TWITTER_ID} 
ENV TWITTER_SECRET ${TWITTER_SECRET} 

ENV FACEBOOK_CALLBACK ${FACEBOOK_CALLBACK} 
ENV FACEBOOK_ID ${FACEBOOK_ID} 
ENV FACEBOOK_SECRET ${FACEBOOK_SECRET} 

# Create app directory
RUN mkdir -p /usr/src/micro-auth
WORKDIR /usr/src/micro-auth

# Install app dependencies
COPY ./package.json /usr/src/micro-auth/
COPY ./package-lock.json /usr/src/micro-auth/
RUN npm install

# Bundle app source
COPY . /usr/src/micro-auth

EXPOSE 3000

CMD [ "npm", "start" ]
